spring:
  application:
    name: subscribe-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mail:
    host: smtp.gmail.com
    port: 587
    username: goormplay@gmail.com
    password: goormplay
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: ${SPRING_SERVER_PORT:8085}

#?db 9000, 3306
