spring:
  application:
    name: subscribe-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mail:
    host: smtp.gmail.com
    port: 587
    username: goormplay@gmail.com
    password: goormplay
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://gpadmin:1234@localhost:8761/eureka} # Jenkins 환경변수 EUREKA_URL이 있으면 사용, 없으면 localhost



server:
  port: 9005

#?db 9000, 3306
