apiVersion: v1
kind: ConfigMap
metadata:
  name: subscribe-service-config
  namespace: subscribe
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_SERVER_PORT: "8085"
  EUREKA_URL: http://eureka-service.eureka.svc.cluster.local:8761/eureka
