apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: subscribe-service-secret
  namespace: subscribe
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: subscribe-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: subscribe-service-secret
