apiVersion: v1
kind: Service
metadata:
  name: subscribe-service
  namespace: subscribe
spec:
  selector:
    app: subscribe-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
